modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/trikzon/armor-visibility/issues"
license = "MIT"

[[mods]]
modId = "armor-visibility"
version = "${version}"
displayName = "Armor Visibility"
#updateJSONURL = ""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/armor-visibility"
#credits = ""
authors = "Trikzon"
description = '''
View yours and others' skins through armor.
'''
#logoFile = ""

[[dependencies.armor-visibility]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armor-visibility]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"