modLoader = "javafml"
loaderVersion = "[42,)"
issueTrackerURL = "https://github.com/trikzon/armor-visibility/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "armor_visibility"
version = "${version}"
displayName = "Armor Visibility"
authors = "Trikzon"
description = '''
View yours and others' skins through armor.
'''
#logoFile = ""

[[dependencies.armor_visibility]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armor_visibility]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"
